fix: health check in same step

diff --git a/.github/actions/turborepo-remote-cache/action.yaml b/.github/actions/turborepo-remote-cache/action.yaml
--- a/.github/actions/turborepo-remote-cache/action.yaml
+++ b/.github/actions/turborepo-remote-cache/action.yaml
@@ -30,14 +30,8 @@ runs:
     - shell: bash
       run: npm install
     - shell: bash
-      run: npx turborepo-remote-cache &
-      env:
-        PORT: ${{ inputs.port }}
-        STORAGE_PROVIDER: "google-cloud-storage"
-        STORAGE_PATH: ${{ inputs.storage_path }}
-        GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.google_application_credentials }}
-    - shell: bash
       run: |
+        npx turborepo-remote-cache &
         echo "Waiting for server to become healthy..."
         for i in {1..10}; do
           status=$(curl -s -o /dev/null -w "%{http_code}" "${TURBO_API}/v8/artifacts/status" || echo "000")
@@ -51,4 +45,24 @@ runs:
         done
         echo "Server health check failed after 10 attempts."
         exit 1
+      env:
+        PORT: ${{ inputs.port }}
+        STORAGE_PROVIDER: "google-cloud-storage"
+        STORAGE_PATH: ${{ inputs.storage_path }}
+        GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.google_application_credentials }}
+    # - shell: bash
+    #   run: |
+    #     echo "Waiting for server to become healthy..."
+    #     for i in {1..10}; do
+    #       status=$(curl -s -o /dev/null -w "%{http_code}" "${TURBO_API}/v8/artifacts/status" || echo "000")
+    #       echo "Attempt $i: Received status code $status"
+    #       if [ "$status" -eq 200 ]; then
+    #         echo "Server is healthy."
+    #         exit 0
+    #       fi
+    #       echo "Server not yet healthy. Retrying in 3 seconds..."
+    #       sleep 3
+    #     done
+    #     echo "Server health check failed after 10 attempts."
+    #     exit 1
 
