fix: server health check

diff --git a/.github/workflows/github_actions.yaml b/.github/workflows/github_actions.yaml
--- a/.github/workflows/github_actions.yaml
+++ b/.github/workflows/github_actions.yaml
@@ -34,11 +34,27 @@ jobs:
         cache: 'pnpm'
 
     - name: Run turborepo-remote-cache
-      run: npx turborepo-remote-cache --yes & sleep 5
+      run: npx turborepo-remote-cache@2.2.12
       env:
         STORAGE_PROVIDER: 'google-cloud-storage'
         STORAGE_PATH: ${{ secrets.STORAGE_PATH }}
- 
+
+    - name: Health check
+      run: |
+        echo "Waiting for server to become healthy..."
+        for i in {1..10}; do
+          response=$(curl -s -o /dev/null -w "%{http_code}" "${ TURBO_API }/v8/artifacts/status")
+          echo "Attempt $i: Received status code $status"
+          if [ "$status" -eq 200 ]; then
+            echo "Server is healthy."
+            exit 0
+          fi
+          echo "Server not yet healthy. Retrying in 5 seconds..."
+          sleep 5
+        done
+        echo "Server health check failed after 10 attempts."
+        exit 1
+
     - name: Install dependencies
       run: pnpm install
 
